language: python
python:
  - "2.7"
install:
  - pip install python-coveralls
  - pip install -r requirements.txt
  - python setup.py install
script:
  - nosetests -s --with-coverage --cover-package=circ
after_success:
    - coveralls
